# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.

os: linux
dist: bionic

script:
  - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
  - bash merge_if_success.sh | tee merge.log

after_failure:
  - cat merge.log

notifications:
  slack:
    secure: "Ug9byplvOQ1zxLhATBSeYTuAQPOntpo6vW9eg8WEdIDUpgUHAqp0gwloZvbN64NKvNkowbb6tRPrgjsAhe/skoTBZ
xiQX8z4FEh1eVLG7aLDYbQjAQfIdpftgfW1/subR4XG/3W8Gtimk4r995YEpe/B0+Gd/41odwIxEhtvC5ZQWm7Aq9dptRK2/hjPT
qOTdMeqpZH1q5WBAkIAXj0ggPj8ibCZGAp0AJDFs68gmi29ALyvXDeMn9lCarIQtkO0PDTa54mAphYCDLm4A2o1Tw5LsrjyDyoIp
OtpdrXcoGV9QnaRsVcHjcwyuNS/bmBlyRP0p4gGlFrTqdKfOEnnr4Eicf1wnoWqw+DBWQ0xFeGOE+OAn7m8qH0AaoxTKHybHYuHv
Hsp60XXsMgEAWF14Lfk3yBuo3LMXPezTtYbSb09F7lMFzrhllWoSKsA0j01+Ss0uT0KdDxCbDUNPBajJFiiatVJymMfqvsFBdeHT
ieMMeh8TcmQXVD/i2HJrDQ9qI7qRxP74RHMl0/R3Hct9aNUJj7srxvwuneUv0rfH3qQnQXgxsQVpyB9T2EVoH9tOnjcElP9ArAfN
i6nuxnrYL38c4FV72Sn5ULJlw98D8OziNuHLCql/SLD5g1lXzYLr+7Tli/sGnrXL7N+JzpjJkcgoul/XjjfD2M0sdZ3ajU="


env:
  global:
    # SLACK_TOKEN
    - secure: "Xge/5Dzn4RrAw8UZke0KLyVOPxPTe9k+Jr8EMWGIXdcXNzzROjdF2KhADLLqINKYJmUtig5vV/RefMTRoqJL4Qu7a0+wtyA6HM7KEVCtNDWJrg1Cg00EbgvtqTfEMvaiT07lfG2Q7JAYE4Hgepi8sflAOkR1G3//YfH48ZxbxzYSWbduySolYR7ecaiksf2L97zUApnyw5vBQ0QmuNeTtcBkfAQTLbYRaUDNsFs4Te7axXhZ+NiF2PgBXhWvorp4yruK8oIo3GyQoPvfwDxyRbryVi+6/tSCQJkTIfUOX+XcK8yv64Mqg8i3reKyQAF7V7R0D8Agi+gdgmyiYEDAQ1P60xp9qFaGQH/qSPaKcnAVRDMag+yIHuam509bBh0c8vdujTPVK0P+tiytX8fzQcG/QWVPTLsSs8UGQwJKu/Po4TxnJk9YvdZp6mw6uu+ogI/vPnrWRhrqwPzU5v21FKDJfOKuScG6FAPagxbC3UqobO/T0TjwzJcwYItemS1vcz0CZo9xKYeRbrJ4hGF1KWuYBhnpEQc0+PE0tgbe4r3aAsz8FZM200WRW/OvyRXNoup9NJ75ZN8dEqGUshDI75YxmthIr9XwwCYHI18RJQfPF9BbQTijPJhwL6c8e4a460oh6Nok+KtqiW3Eg00DHuR0qEujpebQgGagU3Ptacc="

    # GITHUB_TOKEN
    - secure: "C08kt21UJ+ID/eKYos9PfPX3xu+NrmOSTk/SGf7dBg1jDV5atvhoJO8tHRGtFNSeNVrNAhDofUnq539pVuqGZNZbIHQ38C2rct7JnZmd0jOUZiLhK6+j6VUjMXqceFILpQ1/2ELQ0PGpq0Eyuyvl1LKlIOWs3zXK7JT32ZXfdXTEantjT6C9VwsoIKj7LPhzarDaMlmi4QLAC4HR0kTnpjfxYbwhPPw0fT7W6MSuaMTpQDuQ0JxczTeATL+ciLGgBx1P/cuD9du9HOa6QCgzSLosO/KVhqnledjjEH6bJHXCFH2DZ4aepIt4X5u1Nx1xPSbtwhupYOCYSKla6ctfYwVT4RXSIyJrTv004Nm4GxYCV/QPhugbWePPxIqSWmU76xUVpKQcr+WGIwtrBtAyR86a5GVq8B3UCIZOM/WzWicIMYfmf9eMtIxOFCElnLxsWNkF6vC3b8pQpwxK6QrStiry34hHQLn6Zn3wS2PQwq3yk3ytWSyzrPYxTWOpLErJixLPv0hbOU5m2J1glcRQ1VXhWfiqrILqZavKsljeJHZMLiJSBfvcrtIIdHwVTMiyk9nHWg9QaPlopeJEYTmDvozvS676nzPrGEonuPSzYEDcgUwJX2GNXpeizGkwXIG18FDL1kNKeuGcRs45eocxkABFPjKw3xyQko6epR+AHmU="


    # TRAVIS_TOKEN
    - secure: "MDEUWReYY8oUkL5lYOclKQ4AwxZDkQ2Ker543L1BjyANEkRvQWOJtPEK7D0Jom1lilGAi+lFRqmv/K3a5Sd23oMP4IgLDnfY00QUN1M9LUFIuMZJcpWWhABC9oqtaYumub+xFS5LaRg6MX/NWxSbOHIPId+g9W2h5vd0QlG1lGaOOP0EOS2nMI79bay+y7M/s26H+mNAkX99MZaJIoXl9IU4YBZtC9zLgDsdM2nKQ02j4hIEnq61uaJpSNF+ldx0tiQTvcl3wf+i5e2ZE+gZaYM1ET+gIFT7Mb8fsGJGEe6Cwh9pf6caDpCeuUsFCO5j/8TQTUB8WrOYRp9P+r2LbdUAYIU2USAepUZGQwlA8nAcOU9xLsvRRLJwPdOtzrdkO4qRI086Niw5DcCRL/Nzi7jXfnlbgrR3Z8JETwK5ZM9G/HS5+ymmieqo5l7B2nxOSawKJLXHnMi6cnsWZL6gKHCfc1kaWUP2FsKMdta9VBeEFyWUKaAPf9u6nSMgs29lk6hlTEX6+Ea/UyzeZME+ChhgXxunKAdoY0TMSbwE0x1ZOI7uf2nAw5FWg1DqSkrSvt4QZhdu/edf3sVgnZw7tU58T8weB/IYuR4xEn8tO54bX7DMYBha4p0zDjd0uvzdIus7Jdvl9SHddicFkAsER1YEsOTTojOD2UW3HqY3iqM="

    # TRAVIS_AUTH_TOKEN
    - secure: "rprnI80Q2B1EnIZJBS6D6jCG/3nF9dnD+rZXIxatFIjoaiDSXll36c198OTbGkd+vMfrYwdA2USX42bZijQ8hMMhJ9p4VjS3ECIPbf5dBCK/4rfGL/W6tSrIy8QBYJAEGGPB1oxxMJXbXw6IAMvoNtzBo4E9Vd9eKcmdAooa00wlsiUY2Wrurhx2LXAnEfZP3t2X03UQ00NOzz0B4mZe35EiwB6N7z8GFcfyXUrW2nSGsjh3HopHfxMThRd1LrHyy0BlNcuDSQPEqmD9E3c3lf/ElgMINoMV9hbFBH2TRvuEzWDTwm78LK60h7eoWMBsuAv+NZx3LrkDessPo6fKEar5jjUhI3BUY17WGIww5tfyOJdhqDOjESV6ixtdgC3H0+AOvvaaPPC2/sf7F99qIAbLDUXNFiuxtl7MiyV/WSkLBu1FFEJUnppXm5HyEAL95IxrQTlK46DtKzrzLLg2YbZrMp8XQhzTqjK68aTA6Edg+fFx90lOFOV78521YO6YsFLDGz8ctBnsztvOCiyq5EFQhqtzrh0vQTK2TbJySM95T3YFMVOkcJDJjCibOh6DJME7dXZBbgP6K9jx80s+EoW9DozFdxvnl2p+JBPrTG9u7k7NqhBq0lSi6Cp054dprLVGs/s2t4/PHPpPW75PzVKYvbF1I6xqn8J10/miYI4="
