# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.

os: linux
dist: bionic


script:
  - git clone https://github.com/louiscklaw/GithubScripts.git .github_scripts
  - /bin/bash ./.github_scripts/travis/ci-build.sh

import:
  - credentials.yml
  - .travis-merger.yml
